---
- name: Update Proxmox Nodes Sequentially
  hosts: proxmox_nodes
  serial: 1
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 86400
      when: ansible_distribution == "Debian"
